version: '3.9'
services:
  api:
    build: .
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - ollama
  frontend:
    build: .
    command: python3 -m http.server 3000 --directory frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
volumes:
  ollama_models:
